package com.ryh.demo.mapper;

import com.ryh.demo.po.NosqlDb;
import org.springframework.stereotype.Repository;


@Repository
public interface NosqlDbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nosql_db
     *
     * @mbg.generated Fri Dec 11 22:29:54 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nosql_db
     *
     * @mbg.generated Fri Dec 11 22:29:54 CST 2020
     */
    int insert(NosqlDb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nosql_db
     *
     * @mbg.generated Fri Dec 11 22:29:54 CST 2020
     */
    int insertSelective(NosqlDb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nosql_db
     *
     * @mbg.generated Fri Dec 11 22:29:54 CST 2020
     */
    NosqlDb selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nosql_db
     *
     * @mbg.generated Fri Dec 11 22:29:54 CST 2020
     */
    int updateByPrimaryKeySelective(NosqlDb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nosql_db
     *
     * @mbg.generated Fri Dec 11 22:29:54 CST 2020
     */
    int updateByPrimaryKey(NosqlDb record);
}