package com.ryh.demo.mapper;

import com.ryh.demo.po.RTaskSuccess;
import org.springframework.stereotype.Repository;

@Repository
public interface RTaskSuccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtask_success
     *
     * @mbg.generated Sat Dec 12 14:31:32 CST 2020
     */
    int deleteByPrimaryKey(String rwlsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtask_success
     *
     * @mbg.generated Sat Dec 12 14:31:32 CST 2020
     */
    int insert(RTaskSuccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtask_success
     *
     * @mbg.generated Sat Dec 12 14:31:32 CST 2020
     */
    int insertSelective(RTaskSuccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtask_success
     *
     * @mbg.generated Sat Dec 12 14:31:32 CST 2020
     */
    RTaskSuccess selectByPrimaryKey(String rwlsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtask_success
     *
     * @mbg.generated Sat Dec 12 14:31:32 CST 2020
     */
    int updateByPrimaryKeySelective(RTaskSuccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtask_success
     *
     * @mbg.generated Sat Dec 12 14:31:32 CST 2020
     */
    int updateByPrimaryKey(RTaskSuccess record);
}