package com.ryh.demo.mapper;

import com.ryh.demo.po.RTaskRwdd;
import org.springframework.stereotype.Repository;

@Repository
public interface RTaskRwddMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtask_rwdd
     *
     * @mbg.generated Sat Dec 12 14:31:11 CST 2020
     */
    int deleteByPrimaryKey(String rwlsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtask_rwdd
     *
     * @mbg.generated Sat Dec 12 14:31:11 CST 2020
     */
    int insert(RTaskRwdd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtask_rwdd
     *
     * @mbg.generated Sat Dec 12 14:31:11 CST 2020
     */
    int insertSelective(RTaskRwdd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtask_rwdd
     *
     * @mbg.generated Sat Dec 12 14:31:11 CST 2020
     */
    RTaskRwdd selectByPrimaryKey(String rwlsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtask_rwdd
     *
     * @mbg.generated Sat Dec 12 14:31:11 CST 2020
     */
    int updateByPrimaryKeySelective(RTaskRwdd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtask_rwdd
     *
     * @mbg.generated Sat Dec 12 14:31:11 CST 2020
     */
    int updateByPrimaryKey(RTaskRwdd record);
}