package com.ryh.demo.mapper;

import com.ryh.demo.po.RTaskGiveup;
import org.springframework.stereotype.Repository;

@Repository
public interface RTaskGiveupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtask_giveup
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    int deleteByPrimaryKey(String rwlsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtask_giveup
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    int insert(RTaskGiveup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtask_giveup
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    int insertSelective(RTaskGiveup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtask_giveup
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    RTaskGiveup selectByPrimaryKey(String rwlsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtask_giveup
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    int updateByPrimaryKeySelective(RTaskGiveup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtask_giveup
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    int updateByPrimaryKey(RTaskGiveup record);
}