package com.ryh.demo.po;

import java.io.Serializable;
import java.util.Date;

public class RTaskGiveup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rtask_giveup.RWLSH
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    private String rwlsh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rtask_giveup.RWBS
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    private String rwbs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rtask_giveup.CSCS
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    private Integer cscs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rtask_giveup.ZXSJ
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    private String zxsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rtask_giveup.ZXZT
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    private Integer zxzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rtask_giveup.ERRMSG
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    private String errmsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rtask_giveup.LASTUPDATE
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    private Date lastupdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rtask_giveup
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rtask_giveup.RWLSH
     *
     * @return the value of rtask_giveup.RWLSH
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    public String getRwlsh() {
        return rwlsh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rtask_giveup.RWLSH
     *
     * @param rwlsh the value for rtask_giveup.RWLSH
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    public void setRwlsh(String rwlsh) {
        this.rwlsh = rwlsh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rtask_giveup.RWBS
     *
     * @return the value of rtask_giveup.RWBS
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    public String getRwbs() {
        return rwbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rtask_giveup.RWBS
     *
     * @param rwbs the value for rtask_giveup.RWBS
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    public void setRwbs(String rwbs) {
        this.rwbs = rwbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rtask_giveup.CSCS
     *
     * @return the value of rtask_giveup.CSCS
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    public Integer getCscs() {
        return cscs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rtask_giveup.CSCS
     *
     * @param cscs the value for rtask_giveup.CSCS
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    public void setCscs(Integer cscs) {
        this.cscs = cscs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rtask_giveup.ZXSJ
     *
     * @return the value of rtask_giveup.ZXSJ
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    public String getZxsj() {
        return zxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rtask_giveup.ZXSJ
     *
     * @param zxsj the value for rtask_giveup.ZXSJ
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    public void setZxsj(String zxsj) {
        this.zxsj = zxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rtask_giveup.ZXZT
     *
     * @return the value of rtask_giveup.ZXZT
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    public Integer getZxzt() {
        return zxzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rtask_giveup.ZXZT
     *
     * @param zxzt the value for rtask_giveup.ZXZT
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    public void setZxzt(Integer zxzt) {
        this.zxzt = zxzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rtask_giveup.ERRMSG
     *
     * @return the value of rtask_giveup.ERRMSG
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    public String getErrmsg() {
        return errmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rtask_giveup.ERRMSG
     *
     * @param errmsg the value for rtask_giveup.ERRMSG
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    public void setErrmsg(String errmsg) {
        this.errmsg = errmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rtask_giveup.LASTUPDATE
     *
     * @return the value of rtask_giveup.LASTUPDATE
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    public Date getLastupdate() {
        return lastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rtask_giveup.LASTUPDATE
     *
     * @param lastupdate the value for rtask_giveup.LASTUPDATE
     *
     * @mbg.generated Sat Dec 12 14:31:49 CST 2020
     */
    public void setLastupdate(Date lastupdate) {
        this.lastupdate = lastupdate;
    }
}