package com.ryh.demo.po;

import java.io.Serializable;

public class TApp extends TAppKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.APPMC
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    private String appmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.APPJC
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    private String appjc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.URL
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.WBYY
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    private String wbyy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.PXH
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    private Integer pxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.CHECKFLAG
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    private String checkflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.JDBCNAME
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    private String jdbcname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_app
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.APPMC
     *
     * @return the value of t_app.APPMC
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    public String getAppmc() {
        return appmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.APPMC
     *
     * @param appmc the value for t_app.APPMC
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    public void setAppmc(String appmc) {
        this.appmc = appmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.APPJC
     *
     * @return the value of t_app.APPJC
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    public String getAppjc() {
        return appjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.APPJC
     *
     * @param appjc the value for t_app.APPJC
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    public void setAppjc(String appjc) {
        this.appjc = appjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.URL
     *
     * @return the value of t_app.URL
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.URL
     *
     * @param url the value for t_app.URL
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.WBYY
     *
     * @return the value of t_app.WBYY
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    public String getWbyy() {
        return wbyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.WBYY
     *
     * @param wbyy the value for t_app.WBYY
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    public void setWbyy(String wbyy) {
        this.wbyy = wbyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.PXH
     *
     * @return the value of t_app.PXH
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    public Integer getPxh() {
        return pxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.PXH
     *
     * @param pxh the value for t_app.PXH
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    public void setPxh(Integer pxh) {
        this.pxh = pxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.CHECKFLAG
     *
     * @return the value of t_app.CHECKFLAG
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    public String getCheckflag() {
        return checkflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.CHECKFLAG
     *
     * @param checkflag the value for t_app.CHECKFLAG
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    public void setCheckflag(String checkflag) {
        this.checkflag = checkflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.JDBCNAME
     *
     * @return the value of t_app.JDBCNAME
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    public String getJdbcname() {
        return jdbcname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.JDBCNAME
     *
     * @param jdbcname the value for t_app.JDBCNAME
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    public void setJdbcname(String jdbcname) {
        this.jdbcname = jdbcname;
    }
}