package com.ryh.demo.po;

import java.io.Serializable;

public class TAppKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.FYDM
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    private String fydm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.APPID
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_app
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.FYDM
     *
     * @return the value of t_app.FYDM
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    public String getFydm() {
        return fydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.FYDM
     *
     * @param fydm the value for t_app.FYDM
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    public void setFydm(String fydm) {
        this.fydm = fydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.APPID
     *
     * @return the value of t_app.APPID
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.APPID
     *
     * @param appid the value for t_app.APPID
     *
     * @mbg.generated Sat Dec 12 11:11:10 CST 2020
     */
    public void setAppid(String appid) {
        this.appid = appid;
    }
}