package com.ryh.demo.po;

import java.io.Serializable;

public class TsFymc implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_fymc.FYDM
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    private String fydm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_fymc.DM
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    private Short dm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_fymc.FJM
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    private String fjm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_fymc.FDM
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    private Short fdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_fymc.FYMC
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    private String fymc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_fymc.FYJC
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    private String fyjc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_fymc.FYJB
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    private String fyjb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_fymc.TJBM
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    private String tjbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_fymc.SFJY
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    private String sfjy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_fymc.FYDC
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    private String fydc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_fymc.JCYMC
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    private String jcymc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_fymc.JCYJC
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    private String jcyjc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_fymc.FYJC09
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    private String fyjc09;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_fymc.XZQHDM
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    private String xzqhdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ts_fymc
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_fymc.FYDM
     *
     * @return the value of ts_fymc.FYDM
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public String getFydm() {
        return fydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_fymc.FYDM
     *
     * @param fydm the value for ts_fymc.FYDM
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public void setFydm(String fydm) {
        this.fydm = fydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_fymc.DM
     *
     * @return the value of ts_fymc.DM
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public Short getDm() {
        return dm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_fymc.DM
     *
     * @param dm the value for ts_fymc.DM
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public void setDm(Short dm) {
        this.dm = dm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_fymc.FJM
     *
     * @return the value of ts_fymc.FJM
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public String getFjm() {
        return fjm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_fymc.FJM
     *
     * @param fjm the value for ts_fymc.FJM
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public void setFjm(String fjm) {
        this.fjm = fjm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_fymc.FDM
     *
     * @return the value of ts_fymc.FDM
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public Short getFdm() {
        return fdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_fymc.FDM
     *
     * @param fdm the value for ts_fymc.FDM
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public void setFdm(Short fdm) {
        this.fdm = fdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_fymc.FYMC
     *
     * @return the value of ts_fymc.FYMC
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public String getFymc() {
        return fymc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_fymc.FYMC
     *
     * @param fymc the value for ts_fymc.FYMC
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public void setFymc(String fymc) {
        this.fymc = fymc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_fymc.FYJC
     *
     * @return the value of ts_fymc.FYJC
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public String getFyjc() {
        return fyjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_fymc.FYJC
     *
     * @param fyjc the value for ts_fymc.FYJC
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public void setFyjc(String fyjc) {
        this.fyjc = fyjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_fymc.FYJB
     *
     * @return the value of ts_fymc.FYJB
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public String getFyjb() {
        return fyjb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_fymc.FYJB
     *
     * @param fyjb the value for ts_fymc.FYJB
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public void setFyjb(String fyjb) {
        this.fyjb = fyjb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_fymc.TJBM
     *
     * @return the value of ts_fymc.TJBM
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public String getTjbm() {
        return tjbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_fymc.TJBM
     *
     * @param tjbm the value for ts_fymc.TJBM
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public void setTjbm(String tjbm) {
        this.tjbm = tjbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_fymc.SFJY
     *
     * @return the value of ts_fymc.SFJY
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public String getSfjy() {
        return sfjy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_fymc.SFJY
     *
     * @param sfjy the value for ts_fymc.SFJY
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public void setSfjy(String sfjy) {
        this.sfjy = sfjy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_fymc.FYDC
     *
     * @return the value of ts_fymc.FYDC
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public String getFydc() {
        return fydc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_fymc.FYDC
     *
     * @param fydc the value for ts_fymc.FYDC
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public void setFydc(String fydc) {
        this.fydc = fydc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_fymc.JCYMC
     *
     * @return the value of ts_fymc.JCYMC
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public String getJcymc() {
        return jcymc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_fymc.JCYMC
     *
     * @param jcymc the value for ts_fymc.JCYMC
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public void setJcymc(String jcymc) {
        this.jcymc = jcymc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_fymc.JCYJC
     *
     * @return the value of ts_fymc.JCYJC
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public String getJcyjc() {
        return jcyjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_fymc.JCYJC
     *
     * @param jcyjc the value for ts_fymc.JCYJC
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public void setJcyjc(String jcyjc) {
        this.jcyjc = jcyjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_fymc.FYJC09
     *
     * @return the value of ts_fymc.FYJC09
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public String getFyjc09() {
        return fyjc09;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_fymc.FYJC09
     *
     * @param fyjc09 the value for ts_fymc.FYJC09
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public void setFyjc09(String fyjc09) {
        this.fyjc09 = fyjc09;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_fymc.XZQHDM
     *
     * @return the value of ts_fymc.XZQHDM
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public String getXzqhdm() {
        return xzqhdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_fymc.XZQHDM
     *
     * @param xzqhdm the value for ts_fymc.XZQHDM
     *
     * @mbg.generated Sat Dec 12 11:09:15 CST 2020
     */
    public void setXzqhdm(String xzqhdm) {
        this.xzqhdm = xzqhdm;
    }
}